services:
  notificaion_manager:
    build: ./notifications-manager
    ports:
      - 3000:3000
    depends_on:
      - queue
    env_file:
      - .env.dev
  mailcatcher:
    image: sj26/mailcatcher
    container_name: mail_catcher
    expose:
      - 1025
      - 1080
    ports:
      - 1025:1025
      - 1080:1080
  queue:
    image: rabbitmq:3-management
    container_name: notifications_service_queue
    ports:
      - 5672:5672
      - 15672:15672
